### ISSUE TITLE
How to dump all available values?

### ISSUE THREAD

**Issue by aktentasche** [toptica/python-lasersdk#4]
Hi,
besides some selected values that we log more regularly, we would like to retrieve all available values from our controllers every our. What might be the easiest way to achieve that? Is there a list of all available values as strings for the low level interface (like "laser1:dl:cc:current-set", "..)? Or can we iterate through the members of the synchronous interface?
Thanks!

**Comment by a1rw4lk** [comment]
Hi,
thanks for posting this question. I just want to inform you that I forwarded your question to our Devs. They will get back to you as soon as possible. Sorry for the delay and any inconvenience that it might cause.
Cheers!

**Comment by thtrummer** [comment]
In order to get a list of supported parameters of your DLC pro you can send it a ``tree`` command. This is currently not directly supported by the SDK but can still be achieved the following way:

```python
from asyncio import get_event_loop
from toptica.lasersdk.client import Client, NetworkConnection, DecopError

HOST = '172.16.109.105'

def read_param_list(host):
    async def read_param_list_async(host_async):
        net = NetworkConnection(host_async)
        await net.open()
        await net.write_command_line('(tree)\n')
        result = await net.read_command_line()
        await net.close()
        return sorted([name.split(' ')[0] for name in result.splitlines() if 'PARAM' in name])
    loop = get_event_loop()
    return loop.run_until_complete(read_param_list_async(host))

# Read the list of supported parameters: e.g. ['cc1:board-temp', 'cc1:fpga-fw-ver', ...]
param_names = read_param_list(HOST)

# Print the current value of each parameter
with Client(NetworkConnection(HOST)) as client:
    for param in param_names:
        try:
            print(f'{param} = {client.get(param)!r}')
        except DecopError as error:
            print(f"{error} (for '{param}')")
```

**Comment by a1rw4lk** [comment]
Hi @aktentasche, 
did the provided solution work for you? Can we close the ticket?

**Comment by aktentasche** [comment]
Hi @thtrummer @a1rw4lk yes, I did include it in our monitoring code and it is working as expected.

Thanks!

**Comment by a1rw4lk** [comment]
Happy to hear that :) Thanks for the feedback and happy coding!
