### ISSUE TITLE
NetworkConnection: I/O operation on closed connection

### ISSUE THREAD

**Issue by hellbourne** [toptica/python-lasersdk#5]
Dear Toptica,
I installed your sdk for use with my DL Pro controller. When running the examples from your website (python 3.8) everything works fine. When I try, however, to create an object that calls the DLCpro, for example:
`from toptica.lasersdk.dlcpro.v2_0_3 import DLCpro, NetworkConnection, DeviceNotFoundError, DecopError, UserLevel`

`dlc = DLCpro(NetworkConnection(sys.argv[1]))`
and then trying to call `dlc`,  for example with
`dlc.laser1.dl.pc.voltage_set.get()`
I get the error message mentioned in the title:
`NetworkConnection: I/O operation on closed connection`

I'm sure this is a feature and not a bug, but I would like to have an active DLCpro object at all times for use with a different function that also uses other hardware. Is there a way to do this?

Thanks and Frohe Weihnachten,
Amit

**Comment by thtrummer** [comment]
Dear Amit,

when using the Python `with` statement, the SDK will implicitly call `open()` and `close()` (similar to using a file object in that situation).

If you don’t use it, you need to make these calls explicit:

```
dlc = DLCpro(NetworkConnection(sys.argv[1]))
dlc.open()
print(dlc.laser1.dl.pc.voltage_set.get())
# ...
dlc.close()
```

Happy holidays,
Thomas

**Comment by hellbourne** [comment]
Excellent. Thank you, Thomas. It works.
