### ISSUE TITLE
Please consider supporting all future python versions in requirements specifications

### ISSUE THREAD

**Issue by atom-andrew** [toptica/python-lasersdk#8]
At https://pypi.org/project/toptica-lasersdk/, the package is shown to limit python to less than 3.12 (which was just released):

> Requires: Python >=3.6, <3.12

This python restriction makes it challenging to propagate a python dependency through any downstream dependencies of of a package that uses the toptica-lasersdk.  If this restriction could be set to ">=3.6,<4", things would become a lot simpler for us.  If there is somehow a future incompatibility with some 3.x version of python, then it might make sense to add that restriction when that incompatibility is uncovered, but I don't believefuture python versions should generally be expected to break things.  Please consider relaxing the python requirements to support future 3.x versions of pythons.  Thank you.

**Comment by thtrummer** [comment]
Hello,

we have released a new version that should now work for all future releases of Python. 

Please let us know if any further changes are needed.

Best regards,
Thomas
